
# dbt_project.yml (place at the repo root)
name: "dbx_dbt"          # <-- must be a non-empty string; use only letters, numbers, and underscores
version: "1.0"
config-version: 2

profile: "fivetran"      # Fivetran provides this profile at runtime

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbx_dbt:     # Explicitly set catalog
    +schema: analytics
    +materialized: table
